name: "Close stale issues"

on:
  schedule:
    - cron: "2 3,9,15,21 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  handle-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues and PRs
        uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 40 days with no activity.'
          stale-pr-message: 'This pull request is stale because it has been open 40 days with no activity.'
          days-before-stale: 40
          days-before-close: 20
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: 'awaiting-response, enhancement'
          exempt-pr-labels: 'awaiting-response, enhancement'
          close-issue-message: 'This issue was closed because it has been open 60 days with no activity.'
          close-pr-message: 'This pull request was closed because it has been open 60 days with no activity.'
      - name: Toggle label
        uses: jd-0001/gh-action-toggle-awaiting-reply-label@v2.1.2
        with:
          label: awaiting-response
      - name: ChatGPT first answers
        uses: surestacks/chatgpt-buttler@v0
        with:
          only-labels: question, enhancement
          prompt-preamble: |
            I’ve received a user question about my AzureAssess PowerShell Module. Please check its clarity and completeness. If it’s a simple question and you have an answer, provide it considering common PowerShell issues. Your response will be posted directly on GitHub. Remember to:
            * Address the user directly.
            * Assume the user has technical knowledge.
            * Be concise and friendly.
            * Mention you’re an AI assistant helping with GitHub issues.
            Here’s the user’s question:
          openai-key: ${{ secrets.OPENAI_KEY }}


